### ISSUE TITLE
Compilation errors when using 4.8.1

### ISSUE THREAD

**Issue by jamescookie** [micronaut-projects/micronaut-platform#1971]
### Expected Behavior

Projects compile without errors

### Actual Behaviour

We get compilation errors like this:
```
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler output below.
  error: cannot access <class>$Intercepted
    bad class file: /runner/_work/<dir>/build/classes/java/main/<path>/<class>$Intercepted.class
      undeclared type variable: X
      Please remove or make sure it appears in the correct subdirectory of the classpath.
  1 error
```

### Environment Information

- OS: MacOS
- JDK: 21

### Version

4.8.1

**Comment by jamescookie** [comment]
Probably related to https://github.com/micronaut-projects/micronaut-sourcegen/issues/285

**Comment by jamescookie** [comment]
Works fine with 4.8.2
